# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: funnel

# before:
#   hooks:
#     # commands for go workspaces.
#     - go work sync
#     - go work tidy
#     # you may remove this if you don't need go generate.
#     # this is failing with `go work: unknown command`, so we disable it for now.
#     # - go work exec -v -- go generate ./...

builds:
  - id: funnel
    main: ./cmd/funnel
    binary: funnel
    env: &env
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: &ldflags
      - -s -w
      - -X github.com/karol-broda/funnel/version.Version={{.Version}}
      - -X github.com/karol-broda/funnel/version.BuildDate={{.Date}}
      - -X github.com/karol-broda/funnel/version.GitCommit={{.Commit}}
      - -X github.com/karol-broda/funnel/version.GitTag={{.Tag}}
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: server
    main: ./cmd/server
    binary: server
    env: *env
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: *ldflags
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: funnel
    builds:
      - funnel
    name_template: '{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: server
    builds:
      - server
    name_template: '{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - server
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}-amd64"
    dockerfile: docker/server/Dockerfile
    extra_files:
      - docker/server/entrypoint.sh
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: arm64
    ids:
      - server
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}-arm64"
    dockerfile: docker/server/Dockerfile
    extra_files:
      - docker/server/entrypoint.sh
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/funnel-server:{{ .Tag }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
