[package]
name = "funnel-server"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
funnel-core.workspace = true

anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
dashmap = "6"
http-body-util = "0.1"
ipnetwork = "0.20"
metrics = "0.24"
metrics-exporter-prometheus = "0.16"
quinn.workspace = true
rcgen = "0.13"
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
uuid.workspace = true

# tls
aws-config = "1"
aws-sdk-route53 = "1"
axum-server = { version = "0.8", features = ["tls-rustls"] }
instant-acme = { version = "0.8", features = ["rcgen"] }
lru = "0.16"
reqwest = { workspace = true, features = ["rustls", "json", "query"] }
rustls = { workspace = true, features = ["ring", "logging", "std", "tls12"] }
rustls-pemfile = "2"
x509-parser = "0.18"

[dev-dependencies]
axum-test = "16"
pretty_assertions.workspace = true
sqlx.workspace = true
