use clap::{Arg, Command};
use std::fmt::Write;

pub fn generate(cmd: &Command, mdx: bool) -> String {
    let mut out = String::new();

    if mdx {
        writeln!(out, "---").unwrap();
        writeln!(out, "title: CLI Reference").unwrap();
        writeln!(out, "description: All funnel client commands and flags").unwrap();
        writeln!(out, "---\n").unwrap();
        writeln!(
            out,
            "{{/** this file is autogenerated using `funnel generate-cli-reference --mdx` */}}"
        )
        .unwrap();
    }

    for sub in cmd.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        write_command(&mut out, sub, cmd.get_name(), 2);
    }

    writeln!(out, "## Global Flags\n").unwrap();
    writeln!(out, "| Flag | Description |").unwrap();
    writeln!(out, "| --- | --- |").unwrap();

    for arg in cmd.get_arguments().filter(|a| a.is_global_set()) {
        let flag = format_flag(arg);
        let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
        writeln!(out, "| {flag} | {help} |").unwrap();
    }

    writeln!(out, "| `--version` | Print version and protocol info |").unwrap();
    writeln!(out, "| `--help` | Print help |").unwrap();

    out
}

fn write_command(out: &mut String, cmd: &Command, parent: &str, depth: usize) {
    let full = format!("{parent} {}", cmd.get_name());
    let heading = "#".repeat(depth);

    writeln!(out, "{heading} {full}\n").unwrap();

    if let Some(about) = cmd.get_about() {
        writeln!(out, "{}.\n", about.to_string().trim_end_matches('.')).unwrap();
    }

    let positionals: Vec<_> = cmd.get_arguments().filter(|a| a.is_positional()).collect();

    if !positionals.is_empty() || !has_subcommands(cmd) {
        write!(out, "```bash\n{full}").unwrap();
        for arg in &positionals {
            let name = arg.get_id().as_str();
            write!(out, " <{name}>").unwrap();
        }
        writeln!(out, "\n```\n").unwrap();
    }

    for arg in &positionals {
        let name = arg.get_id().as_str();
        if let Some(help) = arg.get_help() {
            writeln!(out, "`<{name}>` is {help}.\n").unwrap();
        }
    }

    let options: Vec<_> = cmd
        .get_arguments()
        .filter(|a| !a.is_positional() && !a.is_global_set() && !is_builtin(a))
        .collect();

    if !options.is_empty() {
        let has_defaults = options.iter().any(|a| !format_default(a).is_empty());

        if has_defaults {
            writeln!(out, "| Flag | Description | Default |").unwrap();
            writeln!(out, "| --- | --- | --- |").unwrap();
        } else {
            writeln!(out, "| Flag | Description |").unwrap();
            writeln!(out, "| --- | --- |").unwrap();
        }

        for arg in &options {
            let flag = format_flag(arg);
            let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
            let default = format_default(arg);
            if has_defaults {
                let default_cell = if default.is_empty() {
                    String::new()
                } else {
                    format!("`{default}`")
                };
                writeln!(out, "| {flag} | {help} | {default_cell} |").unwrap();
            } else {
                writeln!(out, "| {flag} | {help} |").unwrap();
            }
        }

        writeln!(out).unwrap();
    }

    if let Some(after) = cmd.get_after_long_help() {
        let text = after.to_string();
        if !text.is_empty() {
            writeln!(out, "```bash").unwrap();
            for line in text.lines() {
                writeln!(out, "{}", line.trim()).unwrap();
            }
            writeln!(out, "```\n").unwrap();
        }
    }

    for sub in cmd.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        write_command(out, sub, &full, depth + 1);
    }
}

fn format_flag(arg: &Arg) -> String {
    let mut parts = Vec::new();
    let long = arg.get_long().unwrap_or_else(|| arg.get_id().as_str());

    if let Some(short) = arg.get_short() {
        parts.push(format!("`-{short}`"));
    }
    parts.push(format!("`--{long}`"));

    parts.join(", ")
}

fn format_default(arg: &Arg) -> String {
    let defaults = arg.get_default_values();
    if defaults.is_empty() {
        return String::new();
    }
    defaults
        .iter()
        .map(|d| d.to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join(", ")
}

fn has_subcommands(cmd: &Command) -> bool {
    cmd.get_subcommands().next().is_some()
}

fn is_builtin(arg: &Arg) -> bool {
    matches!(arg.get_id().as_str(), "help" | "version")
}
